# Site settings
author: ℳ
title: Cloud 9: Programming Blog
header-img: img/home-bg.png
email: maryikanu@gmail.com
copyright_name: ℳ
description: > # this means to ignore newlines until "baseurl:"
  "Forecasting Today's Technology Trends"
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  miyekay94

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
